name: PHP Linting
on: push
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: PHP Syntax Checker (Lint) 8.0
        uses: StephaneBour/actions-php-lint@8.0
      - name: PHP Syntax Checker (Lint) 8.1
        uses: StephaneBour/actions-php-lint@8.1
